version: '3'
services:
    web:
        image: nginx:alpine
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./etc/ssl:/etc/ssl"
            - "${NGINX_ROOT_VOL:-./web}:/var/www/html"
            - "./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
        ports:
            - "${NGINX_PORT:-8000}:80"
            - "${NGINX_PORT_SSL:-3000}:443"
        environment:
            - NGINX_HOST=${NGINX_HOST:-localhost}
        command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        restart: always
        depends_on:
            - php
            - mysqldb
    php:
        image: nanoninja/php-fpm:${PHP_VERSION:-latest}
        restart: always
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "${NGINX_ROOT_VOL:-./web}:/var/www/html"
    composer:
        image: "composer"
        volumes:
            - "${NGINX_ROOT_VOL:-./web}/${COMPOSER_DIR}:/app"
        command: install
    myadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - "${PHPMYADMIN_PORT:-8080}:80"
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=${MYSQL_HOST:-mysql}
        restart: always
        depends_on:
            - mysqldb
    mysqldb:
        image: mysql:${MYSQL_VERSION}
        container_name: ${MYSQL_HOST:-mysql}
        restart: always
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE:-test}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
            - MYSQL_USER=${MYSQL_USER:-dev}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD:-dev}
        ports:
            - "${MYSQL_PORT:-8989}:3306"
        volumes:
            - "./data/db/mysql:/var/lib/mysql"
